version: ~> 1.0
# for validation of this file

language: shell 
# shell is equivalient to minimal
# https://docs.travis-ci.com/user/languages/minimal-and-generic/

os: linux

# 18.04
dist: bionic

# Ensure Python 3
python: 3.6

jobs:
  include:
    - name: Path Dependent
      before_install:
      - sudo apt-get install -y python3-setuptools python3-apt python3-pip
      install:
      - pip3 install --user --upgrade pip
      - pip3 install --upgrade keyrings.alt --user
      - pip3 install --user --upgrade setuptools
      - pip3 install --user wheel
      - pip3 install --user -r requirements.txt
      before_script:
      - sudo cp home-local-bin.sh /etc/profile.d/home-local-bin.sh
      - sudo chmod 0644 /etc/profile.d/home-local-bin.sh
      - . /etc/profile
      script:
      - make zsh
      - make yarn
      - . /etc/profile
      - vue --version
      - gridsome --version
