version: ~> 1.0
# for validation of this file

language: shell 
# shell is equivalient to minimal
# https://docs.travis-ci.com/user/languages/minimal-and-generic/

os: linux

# 18.04
dist: bionic

# Ensure Python 3
python: 3.6

jobs:
  include:
    - name: Path Dependent
      before_script:
      - pip3 install --user --upgrade pip
      - pip3 install --upgrade keyrings.alt --user
      - pip3 install --user --upgrade setuptools
      - pip3 install --user wheel
      - pip3 install --user -r requirements.txt
      - sudo cp $(FILE) /etc/profile.d/$(FILE)
      - sudo chmod 0644 /etc/profile.d/$(FILE)
      - . /etc/profile
      script:
      - make zsh
      - make yarn
      - . /etc/profile
      - vue --version
      - gridsome --version
