---
version: ~> 1.0
# for validation of this file

language: shell
# shell is equivalient to minimal
# https://docs.travis-ci.com/user/languages/minimal-and-generic/

os: linux

# 18.04
dist: bionic

# Ensure Python 3
python: 3.6

# For conditional logic for ANISBLE in Makefile
addons:
  hostname: travis

branches:
  only:
    - master

jobs:
  include:
    - name: Linting
      before_install:
        - make bootstrap-before-install
        - nvm install 12.16.1
      install:
        - make bootstrap-install
        - npm install -g markdownlint-cli
      before_script:
        - make bootstrap-before-script
      script:
        - make lint

    - name: Docker, Zsh, Nodejs, and Yarn
      before_install:
        - make bootstrap-before-install
      install:
        - make bootstrap-install
      before_script:
        - make bootstrap-before-script
      script:
        - make docker
        - make zsh
        - make yarn
        - . /etc/profile
        - vue --version
        - gridsome --version
        - nativefier --version
        - markdownlint --version
        - carbon-now --version
        - make ticktick

    - name: Common Apt/Deb Packages (Python, Peek, Timeshift, Flameshot, GitHub CLI, NordVPN, Stacer)
      before_install:
        - make bootstrap-before-install
      install:
        - make bootstrap-install
      before_script:
        - make bootstrap-before-script
      script:
        - make python-three-six-install
        - make python-three-six-supporting
        - make python-three-seven-install
        - make python-three-seven-supporting
        - make python-three-eight-install
        - make python-three-eight-supporting
        - make timeshift
        - timeshift --help
        - make github-cli
        - gh --version
        - make nordvpn
        - nordvpn --version
        - make stacer
        - make wifi-analyzer

    - name: Common Snaps, Chat Clients, Development Tools, Web Browsers
      before_install:
        - make bootstrap-before-install
      install:
        - make bootstrap-install
      before_script:
        - make bootstrap-before-script
      script:
        - make common-snaps
        - make chat-clients
        - make development-tools
        - code --version
        # - codium --version
        # not using currently
        - make web-browsers

    - name: Flatpak - Personal, Office
      before_install:
        - make bootstrap-before-install
      install:
        - make bootstrap-install
      before_script:
        - make bootstrap-before-script
      script:
        - make flatpak
        # - make planner
        - make cherrytree
        - make peek
        - make steam
        - make evolution
        - make libreoffice

    - name: GNOME Preferences and Flameshot
      before_install:
        - make bootstrap-before-install
        - sudo apt install -y gnome-shell gnome-session gnome-terminal
        - sudo apt install -y dconf-gsettings-backend dconf-tools dconf-cli
        - sudo apt install -y gsettings-desktop-schemas
      install:
        - make bootstrap-install
      before_script:
        - make bootstrap-before-script
      script:
        - make flameshot  # fresh install
        - make flameshot  # test not installing when version string matches
        - flameshot --version
        - make flameshot-keybindings
        - make gnome-extensions
        - make gnome-dash-to-dock
        - make gnome-keybindings
        - make gnome-preferences
        - make jetbrains-mono
