---
version: ~> 1.0
# for validation of this file

language: shell
# shell is equivalient to minimal
# https://docs.travis-ci.com/user/languages/minimal-and-generic/

os: linux

# 18.04
dist: bionic

# Ensure Python 3
python: 3.6

# For conditional logic for ANISBLE in Makefile
addons:
  hostname: travis

branches:
  only:
    - master

jobs:
  include:
    - name: Linting
      before_install:
        - bash scripts/before_install_apt_dependencies.sh
        - nvm install 12.16.1
      install:
        - bash scripts/install_python3_dependencies.sh
        - npm install -g markdownlint-cli
      before_script:
        - bash scripts/before_script_path_fix.sh
        - . /etc/profile
      script:
        - make lint

    - name: Docker, Zsh, Nodejs, and Yarn
      before_install:
        - bash scripts/before_install_apt_dependencies.sh
      install:
        - bash scripts/install_python3_dependencies.sh
      before_script:
        - bash scripts/before_script_path_fix.sh
        - . /etc/profile
      script:
        - make docker
        - make zsh
        - make yarn
        - . /etc/profile
        - vue --version
        - gridsome --version

    - name: Common Apt/Deb Packages (Python, Cherrytree, Peek, Timeshift, Flameshot, GitHub CLI, NordVPN, Stacer)
      before_install:
        - bash scripts/before_install_apt_dependencies.sh
      install:
        - bash scripts/install_python3_dependencies.sh
      before_script:
        - bash scripts/before_script_path_fix.sh
        - . /etc/profile
      script:
        - make python-three-six-install
        - make python-three-six-supporting
        - make python-three-seven-install
        - make python-three-seven-supporting
        - make poetry
        - make cherrytree
        - cherrytree --help
        - make peek
        - peek --version
        - make timeshift
        - timeshift --help
        - make github-cli
        - gh --version
        - make nordvpn
        - nordvpn --version
        - make stacer

    - name: Common Snaps, Chat Clients, Development Tools, Web Browsers
      before_install:
        - bash scripts/before_install_apt_dependencies.sh
      install:
        - bash scripts/install_python3_dependencies.sh
      before_script:
        - bash scripts/before_script_path_fix.sh
        - . /etc/profile
      script:
        - make common-snaps
        - make chat-clients
        - make development-tools
        - code --version
        - codium --version
        - make web-browsers

    - name: Flatpak - Personal, Office
      before_install:
        - bash scripts/before_install_apt_dependencies.sh
      install:
        - bash scripts/install_python3_dependencies.sh
      before_script:
        - bash scripts/before_script_path_fix.sh
        - . /etc/profile
      script:
        - make flatpak
        - make planner
        - make steam
        - make evolution
        - make libreoffice

    - name: GNOME Preferences and Flameshot
      before_install:
        - bash scripts/before_install_apt_dependencies.sh
        - sudo apt install -y gnome-shell gnome-session gnome-terminal
        - sudo apt install -y dconf-gsettings-backend dconf-tools dconf-cli
        - sudo apt install -y gsettings-desktop-schemas
      install:
        - bash scripts/install_python3_dependencies.sh
      before_script:
        - bash scripts/before_script_path_fix.sh
        - . /etc/profile
      script:
        - make flameshot
        - flameshot --version
        - make flameshot-keybindings
        - make gnome-extensions
        - make gnome-keybindings
        - make gnome-themes
        - make gnome-preferences
