version: ~> 1.0
# for validation of this file

language: bash 
# bash is equivalient to minimal
# https://docs.travis-ci.com/user/languages/minimal-and-generic/

# 18.04
dist: bionic

# Ensure Python 3
python: 3.6

jobs:
  include:
    - before-script:
      - python3 -m pip install --user --upgrade pip
      - python3 -m pip install --upgrade keyrings.alt --user
	    - python3 -m pip install --user --upgrade setuptools
	    - python3 -m pip install --user wheel
	    - python3 -m pip install --user -r requirements.txt
      - sudo cp $(FILE) /etc/profile.d/$(FILE)
      - sudo chmod 0644 /etc/profile.d/$(FILE)
      - . /etc/profile
    - script:
      - make zsh
      - make yarn
      - . /etc/profile
      - vue --version
      - gridsome --version
