version: ~> 1.0
# for validation of this file

language: bash 
# bash is equivalient to minimal
# https://docs.travis-ci.com/user/languages/minimal-and-generic/

dist: bionic

jobs:
  include:
    - before-script:
      - make bootstrap
      - . /etc/profile
    - script:
      - make zsh
      - make yarn
      - . /etc/profile
      - vue --version
      - gridsome --version
