version: ~> 1.0
# for validation of this file

language: shell 
# shell is equivalient to minimal
# https://docs.travis-ci.com/user/languages/minimal-and-generic/

os: linux

# 18.04
dist: bionic

# Ensure Python 3
python: 3.6

addons:
  hostname: travis

jobs:
  include:
    - name: Path Dependent
      before_install:
      - bash scripts/before_install_apt_dependencies.sh
      install:
      - bash scripts/install_python3_dependencies.sh
      before_script:
      - bash scripts/before_script_path_fix.sh
      - . /etc/profile
      script:
      - make zsh
      - make yarn
      - . /etc/profile
      - vue --version
      - gridsome --version
