---
- hosts: localhost
  connection: local
  roles:
    - {role: iancleary.zsh, tags: ['zsh']}
    - {role: yadm, tags: ['yadm']}
    - {role: hyper, tags: ['hyper']}
    - {role: iancleary.docker, tags: ['docker']}
    # - {role: python, tags: ['python']}
    - {role: yarn, tags: ['nodejs', 'yarn']}
    - {role: pulseaudio, tags: ['pulseaudio']}
    - {role: nautilus-mounts, tags: ['nautilus-mounts']}
    - {role: common-snaps, tags: ['common-snaps']}
    - {role: chat-clients, tags: ['chat-clients']}
    - {role: web-browsers, tags: ['web-browsers']}
    - {role: development-tools, tags: ['development-tools']}
    - {role: timeshift, tags: ['timeshift']}
    - {role: github-cli, tags: ['github-cli']}
    - {role: gnome-dash-to-dock, tags: ['gnome-dash-to-dock']}
    - {role: gnome-extensions, tags: ['gnome-extensions']}
    - {role: gnome-keybindings, tags: ['gnome-keybindings']}
    - {role: gnome-preferences, tags: ['gnome-preferences']}
    - {role: nordvpn, tags: ['nordvpn'],
       when: "ansible_hostname in ['xps', 'desktop', 'runner']"
    }
    - {role: stacer, tags: ['stacer']}
    - {role: flatpak, tags: ['flatpak']}
    # Installed Evolution and LibreOffice with Flatpak
    - {role: wifi-analyzer, tags: ['wifi-analyzer']}
    - {role: app-image, tags: ['app-image']}
    - {role: ulauncher, tags: ['ulauncher']}
    - {role: caffeine, tags: ['caffeine']}
