---
site_name: linux-dev-playbook
site_description: Ansible Configuration of Ubuntu LTS Desktops!
site_url: https://linux-dev-playbook.iancleary.me

theme:
    name: 'material'

repo_name: iancleary/linux-dev-playbook
repo_url: https://github.com/iancleary/linux-dev-playbook
edit_uri: 'blob/main'

nav:
    - Introduction: 'index.md'
    - Start with the Makefile: 'makefile.md'
    - Configure for your Machine: 'variable-overrides.md'
    - Shell Configuration Scripts: 'shell-configuration.md'
    - Dotfiles: 'dotfiles.md'
    - Ansible Playbook Command Examples: 'ansible-playbook-examples.md'
    - Ansible Syntax and Configuration: 'ansible-syntax-and-configuration.md'
    - Authors and Attribution: 'AUTHORS.md'
