---
- hosts: localhost
  connection: local
  roles:
    - {role: zsh, tags: ['zsh']}
    - {role: docker, tags: ['docker']}
    # - {role: python, tags: ['python']}
    - {role: yarn, tags: ['nodejs', 'yarn']}
    - {role: jetbrains-mono, tags: ['jetbrains-mono']}
    - {role: ticktick, tags: ['ticktick']}
    - {role: nautilus-mounts, tags: ['nautilus-mounts']}
    - {role: common-snaps, tags: ['common-snaps']}
    - {role: chat-clients, tags: ['chat-clients']}
    - {role: web-browsers, tags: ['web-browsers']}
    - {role: development-tools, tags: ['development-tools']}
    - {role: timeshift, tags: ['timeshift']}
    - {role: flameshot, tags: ['flameshot']}
    - {role: github-cli, tags: ['github-cli']}
    - {role: gnome-extensions, tags: ['gnome-extensions']}
    - {role: gnome-keybindings, tags: ['gnome-keybindings']}
    - {role: gnome-themes, tags: ['gnome-themes'],
       when: ansible_distribution_version == "18.04"
    }
    - {role: gnome-preferences, tags: ['gnome-preferences']}
    - {role: nordvpn, tags: ['nordvpn'],
       when: "ansible_hostname in ['xps', 'desktop', 'travis']"
    }
    - {role: stacer, tags: ['stacer']}
    - {role: flatpak, tags: ['flatpak']}
    # Installed Evolution and LibreOffice with Flatpak
    - {role: evolution-remove-apt, tags: ['evolution-remove-apt']}
    - {role: libreoffice-remove-apt, tags: ['libreoffice-remove-apt']}
