---
- hosts: all
  # connection: local
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - {role: iancleary.zsh, tags: ['init', 'zsh']}
    - {role: zsh_fonts, tags: ['init', 'fonts']}
    - {role: iancleary.docker, tags: ['init', 'docker']}
    # - {role: python, tags: ['python']}
    - {role: yarn, tags: ['init', 'nodejs', 'yarn']}
    - {role: code, tags: ['init', 'code']}
    - {role: terraform, tags: ['init', 'terraform']}
    - {role: github-cli, tags: ['init', 'github-cli']}
    - {role: flatpak, tags: ['init', 'flatpak']}
    - {role: app-image, tags: ['init', 'app-image']}
    - {role: profile-sync-daemon, tags: ['init', 'profile-sync-daemon']}
    - {role: gnome-sushi, tags: ['init', 'gnome-sushi']}
    - {role: ulauncher, tags: ['init', 'ulauncher']}
    - {role: authy, tags: ['init', 'authy']}

    - {role: zsh_fonts, tags: ['fonts']}

    - {role: yadm, tags: ['dotfiles,yadm']}

    - {role: gnome-dash-to-dock, tags: ['gnome', 'gnome-dash-to-dock']}
    - {role: gnome-extensions, tags: ['gnome', 'gnome-extensions']}
    - {role: gnome-keybindings, tags: ['gnome', 'gnome-keybindings']}
    - {role: gnome-preferences, tags: ['gnome', 'gnome-preferences']}

    - {role: hyper-v, tags: ['hyper-v']}

    - {role: pulseaudio, tags: ['host', 'pulseaudio']}
    - {role: nordvpn, tags: ['host', 'nordvpn']}
    - {role: stacer, tags: ['host', 'stacer']}
    # Installed Evolution and LibreOffice with Flatpak
    - {role: wifi-analyzer, tags: ['host', 'wifi-analyzer']}
    - {role: caffeine, tags: ['host', 'caffeine']}
    - {role: timeshift, tags: ['host', 'timeshift']}

    - {role: nautilus-mounts, tags: ['nautilus-mounts']}
    - {role: common-snaps, tags: ['common-snaps']}
    - {role: chat-clients, tags: ['chat-clients']}
    - {role: web-browsers, tags: ['web-browsers']}
    - {role: development-tools, tags: ['development-tools']}
    - {role: hyper, tags: ['hyper']}
