---
- name: install dconf-editor
  become: true
  apt:
    name: "dconf-editor"
    state: present

- name: Preferences
  dconf:
    key: "{{ item.key}}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ gnome_preferences }}"
