---
- name: LibreOffice - remove apt packages
  become: true
  apt:
    name: "{{ item }}"
    state: absent
    purge: "yes"
    autoremove: "yes"
  loop:
    - libreoffice*

- name: LibreOffice - Install LibreOffice via Flatpak
  become: true
  flatpak:
    name: org.libreoffice.LibreOffice
    state: present
