---
- import_tasks: install.yml

- name: Enable antibody shell plugin manager
  include_tasks: antibody.yml
  when: zsh_use_antibody == 'true'

- name: console setup for Debian family distributions
  include_tasks: debian-console-setup.yml
  when: ansible_os_family == 'Debian'
