---
- name: Install flameshot deb from github
  become: true
  apt:
    deb: >-
      {{ flameshot_url }}/v{{ flameshot_version }}/flameshot_{{ flameshot_version }}_bionic_x86_64.deb

- name: account $HOME
  shell: "echo $HOME"
  register: account_homedir
  changed_when: false
  check_mode: "no"

- name: Create autostart directory if it does not exist
  file:
    path: "{{ account_homedir.stdout }}/.config/autostart/"
    state: directory
    mode: "0755"

- name: Make flameshot startup automatically
  copy:
    src: "{{ role_path }}/files/Flameshot.desktop"
    dest: "{{ account_homedir.stdout }}/.config/autostart/Flameshot.desktop"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
