---
- name: Chat Clients - Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Chat Clients - Install Confined Snaps
  become: true
  snap:
    name: "{{ item }}"
  with_items: "{{ snaps_chat }}"

- name: Chat Clients - Install Classicly Confined Snaps
  become: true
  snap:
    name: "{{ item }}"
    classic: "yes"
  with_items: "{{ snaps_chat_classic }}"
