---
- name: Chat Clients - Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Chat Clients - Install Confined Signal and Telegram Snaps
  become: true
  snap:
    name: "{{ item }}"
  loop:
    - "signal-desktop"
    - "telegram-desktop"

- name: Chat Clients - Install Classicly Confined Slack Snap
  become: true
  snap:
    name: "slack"
    classic: "yes"
