---
- name: Evolution - remove apt packages
  become: true
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: "yes"
  loop:
    - evolution-ews
    - evolution

- name: Evolution - Install Evolution (includes EWS) via Flatpak
  become: true
  flatpak:
    name: org.gnome.Evolution
    state: present
