---
- name: Install GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Install PPA
  ansible.builtin.apt_repository::
    repo: ppa:caffeine-developers/ppa
    state: present

- name: Install apt package
  become: true
  apt:
    name: "caffeine"
    state: present
    update_cache: "yes"
