---
- name: Install yadm Deb
  become: "yes"
  apt:
    name: "yadm"

- name: Check if .config/yadm/repo.git/ exists
  stat:
    path: "~/.config/yadm/repo.git/"
  register: stat_result

- name: Clone and bootstrap
  command: yadm clone -b {{ yadm_dotfiles_branch }} {{ yadm_dotfiles_repo }} --bootstrap
  when: not stat_result.stat.exists
