---
- name: Snaps - Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Install Authy
  become: true
  snap:
    name: "authy"
    channel: "beta"
    classic: "no"