
- name: Docker - install apt package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Docker - Add Docker's official GPG Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker - Setup Stable Repository 18.04
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  when: ansible_distribution_version == "18.04"

- name: Docker - Setup Stable Repository 20.04
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  when: ansible_distribution_version == "20.04"

- name: Docker - install Docker CE and containerd packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Docker - Create the docker group
  group:
    name: docker
    state: present

- name: Docker - Add your user to the group
  user:
    name: "{{ ansible_user }}"
    groups: ["docker"]
    append: yes

- name: Docker - Start Docker on boot
  service:
    name: "docker"
    enabled: yes
