
- name: install Docker apt package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker's official GPG Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install Docker CE and containerd packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Create the docker group
  group:
    name: docker
    state: present

- name: Add your user to the group
  user:
    name: "{{ ansible_user }}"
    groups: ["docker"]
    append: yes

- name: Start Docker on boot
  service:
    name: "docker"
    enabled: yes
