---
- name: Cherrytee - Add PPA
  become: true
  apt_repository:
    repo: ppa:giuspen/ppa
    state: present

- name: Cherrytree - Install apt package
  become: true
  apt:
    name: "cherrytree"
    state: present
