---
name: Test

on: push

env:
  hostname: runner

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: before_install
        run: |
          make bootstrap-before-install
          npm install -g markdownlint-cli
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: lint
        run: |
          make lint
  zsh-nodejs-yarn:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: ZSH Antibody
        run: make zsh
      - name: Yarn
        run: make yarn
      - name: Update Github Actions Path
        run: echo "::add-path::/home/runner/.yarn/bin"
      - name: Check Versions
        run: |
          vue --version
          gridsome --version
          nativefier --version
          markdownlint --version
          carbon-now --version
      - name: TickTick
        run: make ticktick

  python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Python 3.8
        run: |
          make python-three-eight-install
          make python-three-eight-supporting

  common-apt-deb-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Timeshift
        run: make timeshift
      - name: Github CLI
        run: |
          make github-cli
          gh --version
      - name: Stacer
        run: make stacer
      - name: Wifi Analyzer
        run: make wifi-analyzer
      - name: Pulse Audio
        run: make pulseaudio
      - name: App Image Launcher
        run: make app-image

  common-snaps:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Common Snaps
        run: make common-snaps
      - name: Chat Clients
        run: make chat-clients
      - name: Development Tools
        run: |
          make development-tools
          code --version
      - name: Web Browsers
        run: make web-browsers

  flatpak:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: flatpak
        run: make flatpak
      - name: CherryTree
        run: make cherrytree
      - name: Peek
        run: make peek
      - name: Steam
        run: make steam
      - name: Evolution
        run: make evolution
      - name: Libreoffice
        run: make libreoffice

  gnome-preferences-hyper-flameshot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
          sudo apt install -y gnome-shell gnome-session gnome-terminal
          sudo apt install -y dconf-gsettings-backend dconf-editor dconf-cli
          sudo apt install -y gsettings-desktop-schemas
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Flameshot
        run: make flameshot
      - name: Flameshot (check idempotence)
        run: make flameshot
      - name: Flameshot version
        run: flameshot --version
      - name: Flameshot keybindings
        run: make flameshot-keybindings
      - name: GNOME Preferences
        run: |
          make gnome-extensions
          make gnome-dash-to-dock
          make gnome-keybindings
          make gnome-preferences
      - name: Jetbrains Mono
        run: make jetbrains-mono
      - name: Hyper
        run: make hyper
