name: Test

on: push

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Pull Docker Image
      #   run: docker pull iancleary/ubuntu1804-ansible-desktop
      # - name: Start Docker Container with volume map
      #   run: docker start -i-t -v &GITHUB_WORKSPACE:/
      - name: before_install
        run: |
          make bootstrap-before-install
          nvm install 12.16.1
      - name: install
        run: |
          make bootstrap-before-script
      - name: script
        run: |
          make lint
