---
name: Test

on: push

env:
  hostname: runner

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: init
        run: |
          make init-github-runner
      - name: Update Github Actions Path
        run: echo "/home/runner/.yarn/bin" >> $GITHUB_PATH
      - name: Check Versions
        run: |
          npm --version
          yarn --version
          vue --version
          nativefier --version
          markdownlint --version
          carbon-now --version
          gh --version

  python:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Python 3.8
        run: |
          make python-three-eight-install
          make python-three-eight-supporting

  common-apt-deb-packages:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Timeshift
        run: make timeshift
      - name: Stacer
        run: make stacer
      - name: Wifi Analyzer
        run: make wifi-analyzer
      - name: Pulse Audio
        run: make pulseaudio
      - name: App Image Launcher
        run: make app-image
      - name: Application Launcher
        run: make ulauncher
      - name: Caffeine
        run: make caffeine

  common-snaps:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Common Snaps
        run: make common-snaps
      - name: Chat Clients
        run: make chat-clients
      - name: Development Tools
        run: |
          make development-tools
          code --version
      - name: Web Browsers
        run: make web-browsers

  flatpak:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: flatpak
        run: make flatpak
      - name: CherryTree
        run: make cherrytree
      - name: Peek
        run: make peek
      - name: PDFSlicer
        run: make pdf-slicer

  gnome-preferences-hyper-flameshot:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: before_install
        run: |
          make bootstrap-before-install
          sudo apt install -y gnome-shell gnome-session gnome-terminal
          sudo apt install -y dconf-gsettings-backend dconf-editor dconf-cli
          sudo apt install -y gsettings-desktop-schemas
      - name: before_script
        run: |
          make bootstrap-before-script
      - name: install
        run: |
          make bootstrap-install
      - name: Setup Inventory and Group Vars for Hostname
        run: make setup_inventory_and_group_vars
      - name: Flameshot
        run: make flameshot
      - name: Flameshot (check idempotence)
        run: make flameshot
      - name: Flameshot version
        run: flameshot --version
      - name: Flameshot keybindings
        run: make flameshot-keybindings
      - name: GNOME Preferences
        run: make gnome
      - name: Hyper
        run: make hyper
