name: CI

on: [push]

jobs:
  test-certain-targets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Stacer install
      run: make stacer
    - name: Timeshift install
      run: make timeshift
    - name: GitHub CLI install
      run: make github-cli
    - name: Flameshot install
      run: make flameshot-install
    - name: Docker install
      run: make docker
    - name: Docker-compose install
      run: make docker-compose
    - name: Python 3.6 install
      run: make python-three-six-install
    - name: Python 3.6 supporting
      run: make python-three-six-supporting
    - name: Python 3.7 install
      run: make python-three-seven-install
    - name: Python 3.7 supporting
      run: make python-three-seven-supporting
    - name: Yet Another Dotfile Manager
      run: make yadm
    - name: Yarn (and Nodejs)
      run: make yarn
    - name: Yarn Globals
      run: make yarn-globals
    - name: Snap Installs
      run: |
        make code
        make chromium
        make postman
        make secure-comms
        make slack
        make spotify
        make sublime-text
        make standard-notes
    - name: Zsh and oh-my-zsh
      run: make zsh
