name: CI

on: [push]

jobs:
  path-dependent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zsh and oh-my-zsh
      run: make zsh
    - name: Yarn (and Nodejs)
      run: |
        make yarn
        . /etc/profile
        vue --version
        gridsome --version

  common:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Common
      run: make common
    - name: Cherrytree
      run: make cherrytree
    # - name: Python
    #   run: make python
    - name: Peek
      run: make peek
    - name: Timeshift
      run: make timeshift
    - name: Flameshot
      run: make flameshot
    - name: GitHub CLI
      run: make github-cli
    # - name: GNOME Extensions
    #   run: make gnome-extensions
    # - name: GNOME Keybindings
    #   run: make gnome-keybindings
    # - name: GNOME Themes
    #   run: make gnome-themes
    # - name: GNOME Preferences
    #   run: make gnome-preferences
    - name: Nordvpn
      run: make nordvpn
    - name: Stacer
      run: make stacer
    # - name: Yet Another Dotfile Manager
    #   run: make yadm

  snap-common:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Snaps - Common
      run: make snaps

  snap-firefox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Firefox
      run: make firefox

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker
      run: make docker

  flatpak-personal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Flatpak
      run: make flatpak
    - name: Planner
      run: make planner
    - name: Steam
      run: make steam

  flatpak-office:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Flatpak
      run: make flatpak
    - name: evolution
      run: make evolution
    - name: LibreOffice
      run: make libreoffice
